language: rust

# Test all 3 channels
rust:
  - stable
  - beta
  - nightly

# And both OSes
os:
  - linux
  - osx

# Breakages in nightly do not fail the overall build
matrix:
  allow_failures:
    - rust: nightly

before_install:
  # Install sdl2 on OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install sdl2 sdl2_image sdl2_ttf; fi
  # Install sdl2 on Linux
  # - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ...; fi