[package]
name = "war-against-machines"
version = "0.1.0"
authors = ["Expenses <expenses@airmail.cc>"]

[dependencies]
rand = "*"
pathfinding = "*"
ord_subset = "*"

[dependencies.sdl2]
version = "*"
features = ["image", "ttf"]

