[package]
name = "war-against-machines"
version = "0.1.3"
authors = ["Expenses <expenses@airmail.cc>"]

[dependencies]

## General

# Random number generation
rand = "*"
# Unit pathfinding
pathfinding = "*"
# For the ability to use 'min_by_key' with f32s
ord_subset = "*"
# For 'retain_mut'
odds = "*"
# Serialization/deserialization
serde = "*"
serde_derive = "*"
## Human-readable settings
toml = "*"
## Efficiently-serialized data
bincode = "*"

## Engine

# Base piston dependencies
piston = "*"
piston2d-graphics = "*"

# Glutin for windowing
pistoncore-glutin_window = "*"

# OpenGL backend
piston2d-opengl_graphics = "*"

# Loading images
image = "*"