[package]
name = "assault"
version = "0.1.0"
authors = ["Expenses <expenses@airmail.cc>"]

[dependencies]
ggez = { git = "https://github.com/expenses/ggez", branch = "events_with_ctx" }
rand = "0.3.15"
pathfinding = "0.1.11"

[profile.dev]
opt-level = 1
