[package]
name = "war-against-machines"
version = "0.2.0"
authors = ["Expenses <expenses@airmail.cc>"]

[dependencies]

# General
## Random number generation
rand = "*"
## Unit pathfinding
pathfinding = "*"
## For the ability to use 'min_by_key' with f32s
ord_subset = "*"
## For 'retain_mut'
odds = "*"

# Serialization/deserialization
serde = "*"
serde_derive = "*"
## Human-readable settings
toml = "*"
## Efficiently-serialized data
bincode = "*"

# Resource loading
## Loading images
image = "*"
## Loading and playing sounds
rodio = "*"

# Engine
## Gfx backend over OpenGL
gfx = {git = "https://github.com/gfx-rs/gfx", rev = "eef868805f2036009fd668272fb39e5e6909dd9c"}
gfx_device_gl = {git = "https://github.com/gfx-rs/gfx", rev = "eef868805f2036009fd668272fb39e5e6909dd9c"}
gfx_window_glutin = {git = "https://github.com/gfx-rs/gfx", rev = "eef868805f2036009fd668272fb39e5e6909dd9c"}
## Windowing
glutin = "*"